# Generated by Django 5.0.1 on 2024-01-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': ['продукты'], 'verbose_name_plural': ['продукция']},
        ),
    ]
